// @flow

import nodemailer from 'nodemailer';
import { emailPassword } from '../secrets.json';

const from = 'r.mark.volkmann@gmail.com;';
// emailPassword is a Google "app password".
// It was generated by browsing
// https://myaccount.google.com/apppasswords,
// entering my Google password,
// scrolling to the bottom,
// selecting "Other" from the "Select App" dropdown,
// entering "nodemailer",
// and pressing the "GENERATE" button.
const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: { user: 'r.mark.volkmann@gmail.com', pass: emailPassword }
});

type EmailType = {
  to: string[],
  subject: string,
  text: string
};

export function sendEmail({ to, subject, text }: EmailType): void {
  const data = { from, to, subject, text };
  transporter.sendMail(data, err => {
    if (err) throw new Error(err);
  });
}
