runtime: nodejs
env: flex
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 4
  cool_down_period_sec: 180
env_variables:
  SQL_USER: postgres
  SQL_PASSWORD: password
  SQL_DATABASE: demo
  INSTANCE_CONNECTION_NAME: node-rest-demo:us-central1:node-rest-demo-db
beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: node-rest-demo:us-central1:node-rest-demo-db
