// flow-typed signature: dbc988cf4d1fe337735c1dac4e2feee0
// flow-typed version: <<STUB>>/express-healthcheck_v^0.1.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-healthcheck'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-healthcheck' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-healthcheck/lib/healthcheck' {
  declare module.exports: any;
}

declare module 'express-healthcheck/test/spec.healthcheck' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-healthcheck/index' {
  declare module.exports: $Exports<'express-healthcheck'>;
}
declare module 'express-healthcheck/index.js' {
  declare module.exports: $Exports<'express-healthcheck'>;
}
declare module 'express-healthcheck/lib/healthcheck.js' {
  declare module.exports: $Exports<'express-healthcheck/lib/healthcheck'>;
}
declare module 'express-healthcheck/test/spec.healthcheck.js' {
  declare module.exports: $Exports<'express-healthcheck/test/spec.healthcheck'>;
}
