// flow-typed signature: 619f70974e798cda399e265b598b4263
// flow-typed version: <<STUB>>/postgresql-easy_v^1.2.4/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postgresql-easy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postgresql-easy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postgresql-easy/demo' {
  declare module.exports: any;
}

declare module 'postgresql-easy/sql-util' {
  declare module.exports: any;
}

declare module 'postgresql-easy/sql-util.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postgresql-easy/demo.js' {
  declare module.exports: $Exports<'postgresql-easy/demo'>;
}
declare module 'postgresql-easy/index' {
  declare module.exports: $Exports<'postgresql-easy'>;
}
declare module 'postgresql-easy/index.js' {
  declare module.exports: $Exports<'postgresql-easy'>;
}
declare module 'postgresql-easy/sql-util.js' {
  declare module.exports: $Exports<'postgresql-easy/sql-util'>;
}
declare module 'postgresql-easy/sql-util.test.js' {
  declare module.exports: $Exports<'postgresql-easy/sql-util.test'>;
}
